query UpcomingLaunches {
	upcomingLaunches @rest(type: "Launch", path: "launches/upcoming") {
		id
		name
		flightNumber
		datePrecision
		rocket
		dateUtc
		dateUnix
		dateLocal
		details
		cores {
			flight
			reused
			landingAttempt
			landingType
		}
		payloads
	}
	rockets @rest(type: "Rocket", path: "rockets") {
		id
		name
		type
	}
	payloads @rest(type: "Payload", path: "payloads") {
		id
		name
		type
		reused
		launch
		customers
		nationalities
		massKg
		orbit
		dragon {
			capsule
		}
	}
}
